name 'tmux_wrapper'
maintainer 'The Authors'
maintainer_email 'taylor.monacelli@streambox.com'
license 'all_rights'
description 'Installs/Configures tmux_wrapper'
long_description 'Installs/Configures tmux_wrapper'
version '0.1.0'
